# Generated by Django 3.0.2 on 2020-02-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('total', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer')),
                ('item', models.ManyToManyField(to='app.Gem')),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_money', models.IntegerField(null=True)),
                ('gems', models.ManyToManyField(to='app.Gem')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer')),
            ],
        ),
    ]
