# Generated by Django 3.0.2 on 2020-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('total', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('spent_money', models.PositiveIntegerField()),
                ('gems', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-spent_money',),
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deals', models.FileField(upload_to='uploads/', verbose_name='csv-файл')),
            ],
        ),
    ]
