# Generated by Django 3.0.2 on 2020-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealsModel',
            fields=[
                ('customer', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('total', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('spent_money', models.IntegerField(null=True)),
                ('gems', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-spent_money',),
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
