# Generated by Django 3.0.2 on 2020-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealsModel',
            new_name='DealModel',
        ),
    ]
