# Generated by Django 3.0.2 on 2020-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='gems',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='choice',
            field=models.FileField(upload_to='uploads/', verbose_name='csv-файл'),
        ),
    ]
