# Generated by Django 3.0.2 on 2020-02-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200202_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='choice',
            new_name='deals',
        ),
    ]
