# Generated by Django 3.0.2 on 2020-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200201_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsmodel',
            name='customer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dealsmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='dealsmodel',
            name='item',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
