# Generated by Django 3.0.2 on 2020-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200201_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='gems',
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='gems',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Gem',
        ),
    ]
