# Generated by Django 3.0.2 on 2020-02-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200201_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ('-spent_money',)},
        ),
    ]
