# Generated by Django 3.0.2 on 2020-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200202_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gems', models.CharField(max_length=50)),
            ],
        ),
    ]
