# Generated by Django 3.0.2 on 2020-02-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jewelsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JewelsModel',
        ),
    ]
